# Generated by Django 6.0 on 2025-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_shipping_fee_alter_order_status'),
        ('payments', '0005_payment_delete_webhookevent_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'initiated'])), fields=('order',), name='one_active_payment_per_order'),
        ),
    ]
