# Generated by Django 5.0.4 on 2026-07-13 18:15

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_order_notes_alter_order_payment_method_and_more'),
        ('payments', '0006_paymenttransaction_one_active_payment_per_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='one_active_payment_per_order',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=payments.models.receipt_upload_path),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('pending_verification', 'Pending Verification'), ('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'initiated', 'pending_verification'])), fields=('order',), name='one_active_payment_per_order'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
