# Generated by Django 5.0.4 on 2026-07-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_paystack_columns'),
        ('payments', '0008_rename_reference_remove_access_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='one_active_payment_per_order',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending Verification'), ('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'pending_verification'])), fields=('order',), name='one_active_payment_per_order'),
        ),
    ]
