# Generated by Django 5.0.4 on 2026-07-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_performance_indexes'),
        ('payments', '0009_remove_paymenttransaction_one_active_payment_per_order_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payments_pa_status_b6726a_idx'),
        ),
    ]
