services:
  - type: web
    name: vulor
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py migrate --noinput --verbosity=3
    startCommand: gunicorn vulor.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: vulor.settings
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: vulor-db
          property: connectionString
      - key: DEBUG
        value: "False"
databases:
  - name: vulor-db
    databaseName: vulor
    user: vulor_user
