services:
  - type: web
    name: vulor-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn vulor.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: vulor.settings
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: 2
