# Generated by Django 4.2.7 on 2025-11-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_paid_order_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
    ]
