# Generated by Django 4.2.7 on 2025-11-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_options_alter_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notified_cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notified_high_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notified_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='review_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
