# Generated by Django 6.0 on 2025-12-20 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_shipping_fee_order_shipping_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='admin_notified_cancellation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='admin_notified_high_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='admin_notified_new',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_email_sent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paystack_access_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='review_email_sent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_email_sent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_zipcode',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
