# Generated by Django 6.0 on 2025-12-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
