# Generated by Django 6.0 on 2025-12-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
