# Generated by Django 6.0 on 2025-12-28 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_inventory_adjusted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='inventory_adjusted',
        ),
    ]
