# Generated by Django 6.0 on 2025-12-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_inventory_adjusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
