# Generated by Django 4.2.7 on 2025-11-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hip_measurements',
            field=models.TextField(blank=True, help_text='Hip measurements in inches (for cargo jeans and sweatpants)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_measurements',
            field=models.TextField(blank=True, help_text='Length measurements in inches (for cargo jeans and sweatpants)'),
        ),
        migrations.AddField(
            model_name='product',
            name='rise_measurements',
            field=models.TextField(blank=True, help_text='Rise measurements in inches (for cargo jeans)'),
        ),
        migrations.AddField(
            model_name='product',
            name='thigh_measurements',
            field=models.TextField(blank=True, help_text='Thigh measurements in inches (for cargo jeans)'),
        ),
        migrations.AddField(
            model_name='product',
            name='waist_measurements',
            field=models.TextField(blank=True, help_text='Waist measurements in inches (for cargo jeans and sweatpants)'),
        ),
    ]
