# Generated by Django 4.2.7 on 2025-11-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_hip_measurements_product_length_measurements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fit_type',
            field=models.CharField(blank=True, choices=[('loose', 'Loose'), ('fit', 'Fit')], help_text='Only for cargo jeans', max_length=10, null=True),
        ),
    ]
