# Generated by Django 4.2.7 on 2025-11-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_fit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
