# Generated by Django 6.0 on 2025-12-25 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='product',
            name='fit_type',
            field=models.CharField(blank=True, choices=[('loose', 'Loose'), ('fit', 'Fit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hip_measurements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_measurements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rise_measurements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thigh_measurements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='waist_measurements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
