# Generated by Django 6.0 on 2025-12-28 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_category_alter_product_fit_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='fit_type',
            field=models.CharField(blank=True, choices=[('loose', 'Loose'), ('fit', 'Fit')], help_text='Only for cargo jeans', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hip_measurements',
            field=models.TextField(blank=True, help_text='Hip measurements in inches (for cargo jeans and sweatpants)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_measurements',
            field=models.TextField(blank=True, help_text='Length measurements in inches (for cargo jeans and sweatpants)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rise_measurements',
            field=models.TextField(blank=True, help_text='Rise measurements in inches (for cargo jeans)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thigh_measurements',
            field=models.TextField(blank=True, help_text='Thigh measurements in inches (for cargo jeans)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='waist_measurements',
            field=models.TextField(blank=True, help_text='Waist measurements in inches (for cargo jeans and sweatpants)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
