# Generated by Django 5.0.4 on 2026-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_storereview'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('inventory_count__gte', 0)), name='product_inventory_count_non_negative'),
        ),
    ]
